name: Daily Stock Strategy Analysis

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Fetch news
        run: |
          python src/fetch_news.py
      - name: Fetch markets
        run: |
          python src/fetch_markets.py
      - name: Analyze and generate report
        env:
          MODELS_API_KEY: ${{ secrets.MODELS_API_KEY }}
        run: |
          python src/analyze.py
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit and push changes
        run: |
          git add reports/ data/
          git diff --staged --quiet || git commit -m "Daily stock analysis report - $(date +'%Y-%m-%d')"
          git push
